### ISSUE TITLE
Tree view panel don't take into account Tree view menu font options

### ISSUE THREAD

**Issue by Brifien** [doublecmd/doublecmd#1293]
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 10943
Commit: e81933aff
Build date: 2023/09/28
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

But also present on previous versions.

### Description

Tree view panel don't take into account Tree view menu font options (font type, size, ...)

**Comment by alexx2000** [comment]
Not a bug. It is a two different unrelated entities. Tree View Panel use file panel font.

**Comment by antodc** [comment]
@alexx2000 Sorry to come back on this issue. I have set the file panel font to Arial 11 and the tree view panel indeed takes the same font. Hovever, if I close and open DC the font in the tree view panel gets bigger (Arial 12 or 13), while that in the file panel remains the same. The most strange thing is that I tried any Arial with size from 8 to 13 and the issue seems to appear only with 11.

**Comment by antodc** [comment]
> @alexx2000 Sorry to come back on this issue. I have set the file panel font to Arial 11 and the tree view panel indeed takes the same font. Hovever, if I close and open DC the font in the tree view panel gets bigger (Arial 12 or 13), while that in the file panel remains the same. The most strange thing is that I tried any Arial with size from 8 to 13 and the issue seems to appear only with 11.

It also happens only when the settings are such that the Tree View Panel is opened at the startup of DC. In that case, its font has a different size than that of the file panel. If I opens the Tree View Panel after DC is started the two fonts are the same.
