### ISSUE TITLE
Case sensitive "cd" command

### ISSUE THREAD

**Issue by adlabac** [doublecmd/doublecmd#1577]
### Version

Double Commander
Version: 1.1.11 beta
Revision: 410
Commit: f1b449635
Build date: 2024/03/10
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 22H2 x86_64

### Description

Change directory command "cd" does not work if it's written with uppercase letter(s) ("CD", "Cd" or "cD"). It should be case insensitive (on Windows systems, at least).

**Comment by lprot** [comment]
Still reproducible on:

Double Commander
Version: 1.1.13 gamma
Revision: 453
Commit: f60bf09df
Build date: 2024/04/20
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 12.7.4

The reason here is autocorrection (or autoreplace) in command line of Double Commander.
For example if you by mistake entered "Cd '%COMMANDER_PATH'" you cannot correct it to "cd '%COMMANDER_PATH%'" as autoreplace keeps it "Cd '%COMMANDER_PATH'".

@alexx2000 So the best fix here would be to turn off autocorrection in command line that does not let you to correct capital letters to small letter or vice versa.

**Comment by alexx2000** [comment]
@lprot autocomplete disabled in the command line. But looks like it does not work under macOS.
