### ISSUE TITLE
Stuck on deleting a file

### ISSUE THREAD

**Issue by distantrainbow** [doublecmd/doublecmd#190]
A month ago a problem appeared: Double Commander can't delete files. Even a small .mp4 of 18MB stuck the program and the program need to be restarted.
`0% deleting` for long minutes. When I click on `cancel`, it adds the `[stopping]` status, but nothing happens - it doesn't really stop.

Version 0.9.10 beta on Windows 10 build 19043

**Comment by jankuc** [comment]
Very similar thing started to happen to me after upgrading to Win 11. Blank pop-up windows is shown and program crashes. On the other hand the files are correctly deleted. It doesn't crash on small files <2mb. Maybe the because the status bar doesn't appear.
![image](https://user-images.githubusercontent.com/479989/135825824-f4ec29c8-ad14-4174-b977-2ecf9abb1de4.png)

**Comment by distantrainbow** [comment]
> Try DC 1.0 from [snapshots](https://doublecmd.sourceforge.io/site/eng/snapshots.php).

Works good, the problem with deletion resolved.
Also the dark theme is beautiful!
