### ISSUE TITLE
Wrong background with gtk2 theme Gnome OSX-IV-1.3

### ISSUE THREAD

**Issue by shitpoet** [doublecmd/doublecmd#32]
doublecmd 0.9.9 beta has wrong background, when Gnome OSX-IV-1.3 gtk2/gtk3 theme is used.

### Expected behaviour

grayish background for main window background (excluding file lists, of course).

### Actual behaviour

blue background for main window background (excluding file lists, menu and toolbar).

### Steps to reproduce

1. install the theme (unfortunately I do not have a link to it, only source files)
2. apply the theme system-wide or run doublecmd with 

        GTK2_RC_FILES="/path/to/theme/folder/gtk-2.0/gtkrc" doublecmd 

### Version

doublecmd version: 0.9.9 Beta, gtk2, Linux 64-bit
(tar downloaded from sourceforge)
OS: Debian 10 Buster
WM: openbox

### Other info

Screenshot attached.

Theme files are attached.

Other apps in the system look fine. 

Even doublecmd-qt 0.9.1 looks fine, though it uses the same theme through `qt-style-plugins` package. (That package makes qt apps to use gtk2 theme.)

I investigated the problem a little, and found that changing this color

        gtk-color-scheme = "selected_bg_color: #f5f6f7

in `gtkrc` file of `gtk-2.0` folder of the theme changes the color, but as a side effect it also affects text selection color and many other colors, including the colors of the applications spawned by doublecmd.

Because other apps work just fine, I consider this is a bug.

May be someone knows any workaround to it, excluding modification of source code of the doublecmd and recompiling?

![2020-10-04--161759--538021816](https://user-images.githubusercontent.com/6325916/95016704-5a33c700-065d-11eb-8e33-adc98f1ec752.png)

[Gnome OSX-IV-1.3.zip](https://github.com/doublecmd/doublecmd/files/5323271/Gnome.OSX-IV-1.3.zip)

**Comment by shitpoet** [comment]
I managed to workaround the issue by changing this line in theme's `main.rc`

    #bg[PRELIGHT] = @selected_bg_color
    bg[PRELIGHT] = @bg_color

Do not know why doublecmd uses `PRELIGHT` color, and is it correct or not. 

May be it is a bug of the theme itself...

**Comment by jn64** [comment]
Same issue with the [GTK2 HighContrast](https://gitlab.gnome.org/GNOME/gnome-themes-extra/-/tree/master/themes/HighContrast?ref_type=heads) theme:

![screenshot_2023-09-07_17-50-08](https://github.com/doublecmd/doublecmd/assets/23169302/d41e79fd-c3e5-499a-b8b5-c01f002becf7)

This is a Doublecmd bug, not theme bug. Prelight is the state when a mouse is on a widget (aka "hover" state). Specifically, `bg[PRELIGHT]` is used for the background of active widgets like menu bar items (e.g. when you hover over _Files_). All the black areas in my screenshot are inactive/unfocused buttons or simply blank areas and should not be using the `bg[PRELIGHT]` colour.

Editing the theme to change `bg[PRELIGHT]` to a suitable inactive bg colour like white/grey isn't an acceptable workaround in my case because then hovered widgets become too low contrast to read.

**Comment by alexx2000** [comment]
Lazarus bug. I added workaround.
