### ISSUE TITLE
Changing the case in FAT32 filesystem

### ISSUE THREAD

**Issue by Jankosx7** [doublecmd/doublecmd#327]
In the fat32 filesystem changing uppercase to lowercase (or vice versa) of file/folder name
does not work properly.

For example: When you try to rename folder AAA to AAa, the name is still AAA.
This error occurs when changing name by Shift-F6 and also with multi-rename tool.
The error does not occur in ntfs filesystem.
Tested under widows 10 and on a flash drive formatted in fat32.

**Comment by alexx2000** [comment]
It is a known Windows bug. It does not work in the Windows Explorer too.

**Comment by tukanos** [comment]
> In the fat32 filesystem changing uppercase to lowercase (or vice versa) of file/folder name does not work properly.
> 
> For example: When you try to rename folder AAA to AAa, the name is still AAA. This error occurs when changing name by Shift-F6 and also with multi-rename tool. The error does not occur in ntfs filesystem. Tested under widows 10 and on a flash drive formatted in fat32.

This is inherent feature of FAT32.  If you look at the history of FAT (FAT->VFAT->FAT32) it was always a case insensitive system.  Which means the FAT filesystem itself can't differentiate between 'AAA' vs 'AAa' so there is **no way** any application above it can recognize the difference!

Should you need a case sensitive filesystem you need to run NTFS.  However, MS did not make it easy for us so because most of the win32 subsystem is case-insensitive due to FAT history.  You can make different cases at files using low level system calls e.g. [CreateFileA function (fileapi.h)](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea?redirectedfrom=MSDN).  You can now on Windows 10 turn on the case sensitivity for directories - [How to Enable Case Sensitive File and Folder Names on Windows 10](https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/)

You can close this issue because it is not an issue of Double Commander it is a design issue of FAT filesystem.
