### ISSUE TITLE
Archiv issues in Linux

### ISSUE THREAD

**Issue by Offerel** [doublecmd/doublecmd#357]
I have installed DoubeCommander 1.0.4 from official repository's on Manjaro Linux. Basically, the application works so far. But for some reason, i cant use archiving functions. For example, when i try to create a ZIP archive, i get the message, that zip.wcx cant be accessed. However, the file is on the expected location. If i remember right, it is is defined to be on %commander_path%/plugins/wcx/zip/zip.wcx.
If i list this path from within DoubleCommander, i see that the file is there. 

Any idea, what i can do or why the file cant be accessed?

BTW: Is there any 7zip plugin for Linux?

**Comment by alexx2000** [comment]
Don't know why it does not work. I tried doublecmd from Arch package and it works for me.

Under Linux DC use p7zip by default, if it was installed before DC. Otherwise you can install it and enable in DC "Options"->"Archivers".  Also exists read-only 7-Zip plugin, you can download latest built from [here](https://disk.yandex.ru/d/jhgHgkt1ypuhPw/other) , archive dc-plugins-for-ubuntu-20.04-20220205.tar.gz.

Also see [plugins](https://github.com/doublecmd/doublecmd/wiki/Plugins) page at wiki.
