### ISSUE TITLE
New Folder Generation in DOUBLE COMMANDER running on linux mint.

### ISSUE THREAD

**Issue by geoffwarnold** [doublecmd/doublecmd#559]
There does not appear to be a right click context command to create a new folder. A thorough search reveals nothing and I have to generate a new folder in another file manager or on the desktop. Seems to be a major oversight ?

**Comment by alexx2000** [comment]
F7 or Menu->"Files"->"Create Directory", also see [here](https://doublecmd.h1n.ru/viewtopic.php?f=6&t=7351) about context menu.

**Comment by funkymaster** [comment]
I use the F7 and Shift+F4 keys for this actions usually. So, this is not a big issue for me.
But wouldn't it be better to get the "new" context menu in every situation, regardless of whether a folder or file is selected? Because I don't know how to select the background, if the tab is full with folders or files.
It's clear, that some context menu entries should only be available if [Background](https://github.com/doublecmd/doublecmd/blob/ec855c4d0f2d2f2e6130654bd6541e2407108451/src/platform/unix/ushellcontextmenu.pas#L717) is true or not. Like "copy", "move" ...
But for the "new" submenu, this should not be relevant.
I think this is not only related to Unix.

**Comment by geoffwarnold** [comment]
I think that people coming from Windows file manager expect to find a right
click context menu with "New Folder" and a directory is thought of as a
high level guide one step down from a drive. So when you think about it
there is not any particular difference between a folder and a directory -
they are one and the same.
Anyway problem sorted - F7 it is. Thanks for the help.

Regards G.W. Arnold
Mobile  07515 451505
41 Ash Crescent SEAHAM
SR7 7UG
