### ISSUE TITLE
Code migration to Git(Hub)?

### ISSUE THREAD

**Issue by szpak** [doublecmd/doublecmd#6]
The svn2github project was recently [closed](https://piotr.gabryjeluk.pl/blog:closing-svn2github) and the GitHub mirror I've been using to find suspected commits why tracking down issues in my [nightly RPM builds](https://github.com/szpak/doublecmd-rpm) for Fedora is [no longer](https://github.com/svn2github/doublecmd/issues/2) updated.

The SVN UI available at Sourceforge is somehow "problematic to use" (at least for me). It would be really nice to have the project migrated to Git and (at least) mirrored to GitHub (the main Git repository could be at Sourceforge, GitLab or anything else if you @alexx2000 don't like the idea to use GitHub for that).

That, by the way, would allow people to do some minor pull requests via GitHub which could be even merged manually to the main repository (and mirrored to GitHub) - most of the incidental developers don't like to install SVN just to fix some type or documentation.

This is a follow-up of the corresponding old thread on the project [forum](https://doublecmd.sourceforge.io/forum/viewtopic.php?p=23036#p23036). Created here to allow interested "GitHub guys" to know about the status of (potential) migration.

**Comment by cryham** [comment]
As I described in the new topic (yours is older) in [this post](https://doublecmd.sourceforge.io/forum/viewtopic.php?p=26516#p26516), one can use Git (from svn) without svn2github just using `git svn` commands.
Using those 2 commands you can easily create your own mirror repo and update it when you want from svn.

I have [my fork](https://github.com/cryham/dc/commits/ch-fork) and I update [master](https://github.com/cryham/dc/commits/master) from just svn, when I develop and merge (irregular).

When it comes to using git versus svn, my personal opinion is that svn is ancient and because I use git since 2011 I would recommend using it. Link with comparison [gitlab vs github](https://usersnap.com/blog/gitlab-github/). But of course I completely understand developers who don't want to change for any reason. I surely wouldn't want to change webiste/repo myself far after development start.

**Comment by Kissaki** [comment]
Good day,

I love the project and have been using DoubleCmd for a long time. I found it inaccessible both due to svn and sourceforge as well as bugtraq (which is overcomplicated). I strongly believe a move to Git and GitHub would make the project much more accessible to users and developers, and in turn ease entry for new contributors. Git and GitHub has by far the biggest developer and project userbase and using it is basically standard.

I have migrated/converted several SVN projects to Git at work before, and for a FOSS project I migrated (a subselection of) SF tickets to GitHub.

If you want any help regarding a migration or want to discuss anything regarding this I would be glad to help. I would love to see a move happen ASAP; be it partial or full. (I’m glad to see you’re publishing changes/changelog here already.)

I don’t know what your current CI solution is, but Azure could provide free builds as well. (I did experiment with creating a GitHub repo/fork with automated builds before, but have not finished or published anything yet.)

**Comment by cryham** [comment]
There are lots of issues / bug reports on Mantis currently in use too:
https://doublecmd.sourceforge.io/mantisbt/my_view_page.php
I'm pretty sure moving a sizeable project like DC now would be a time consuming trouble.
Still, I think it'd be better to have it all in 1 place like github, and I'd also recommend it. Having CI on top of that would be even greater.

**Comment by dandv** [comment]
We can start by [closing Mantis to new issues](https://github.com/doublecmd/doublecmd/issues/49).

**Comment by szpak** [comment]
> We can start by closing Mantis to new issues.

Especially that there is no email notification in SourceForge's Mantis... Similarly, on the discussion forum.

**Comment by alexx2000** [comment]
Done. Code migrated here.

**Comment by szpak** [comment]
Great! Especially that you preserved the history.

Is it a good assumption that you switch to GitHub for good and for my [nightly Fedora builds](https://github.com/szpak/doublecmd-rpm) I should switch to it? Or it is "just" a mirror and you plan using SVN as the primary SCM?

**Comment by alexx2000** [comment]
It is a main repository. Subversion obsolete and in the read only mode.

**Comment by Neustradamus** [comment]
@alexx2000: Thanks!

The next step is to add all in Releases and Tags sections, can you do it?

**Comment by alexx2000** [comment]
I do not want to add old releases here. New releases will be here.
