### ISSUE TITLE
Manage folders with space character at end

### ISSUE THREAD

**Issue by dapgo** [doublecmd/doublecmd#9]
From Double commander is possible to create a new folder including an space character at the end.  However, Double commander is not able to delete or rename a folder like this.

The worst for en users is that Windows Explorer has  also problems with this folders, so deleting or renaming requires advanced skills(commandline).

IMO, double commander should do one of the following: 
Trim names to avoid spaces at beginning or end
or 
(if technically possible) Being able to delete, rename

**Comment by outfrost** [comment]
Just trimming names is a bad idea, because sometimes it's desired to have very specific characters in names. Also, other platforms actually handle those names correctly, in contrast to Windows.

However, prompting the user if whitespace at the beginning/end of a name is desired or should be trimmed, or if the user wants to go back and edit the name, would probably be quite useful IMO.

**Comment by dapgo** [comment]
At  least I will make an exception and I will trim the space at the end of a name when DC is running on  Windows.  
Because this space is really problematic in Windows, and some users use DoubleCommander and  windows explorer.

**Comment by alexx2000** [comment]
DC trim the space at the end now.
